version: "2"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN #do we need this?
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=test.techjam.io
#      - SUBDOMAINS=www,test
      - VALIDATION=http
      - EMAIL=andy.givens@cyberark.com
#     - DHLEVEL=2048 #optional
#     - ONLY_SUBDOMAINS=false #optional
#     - EXTRA_DOMAINS=extradomains #optional
#     - STAGING=false #optional
    volumes:
      - /srv/letsencrypt/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
        default:
        internal:

  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
    volumes:
      - /srv/CTFd/logs:/var/log/CTFd
      - /srv/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
      - letsencrypt
    networks:
        default:
        internal:

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
    volumes:
      - /srv/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: unless-stopped
    volumes:
    - .data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
      internal: true
